CharacterName: [A]kira
Categories:
  - Charge
    - 46+P+K____
  - Punishable    
    - K+G! #knee
    - 66+KK5 #DoubleKick
    - 466+P+K #BodyCheck
    - 3346+P #DoublePalm
    - 33+P #yoho
    - K+GP
  - Punishable Low
    - 6+P455K #recoverslow
    - 9+G5K #recoverslow
    - 2+K #recoverslow
  - Mixup Jump
    - 9+G5K
    - 9+G5P
    - 9+GK
    - 9+G55P+G