CharacterName: Bla[z]e
Categories:
  - Punish
    - 9+GP
    - 6+K+G #VolcanoKnee
    - 6+PK #ElbowKnee
    - 46+PP52+K
    - 2+G__52+K+G
    - 6+P+K+G559+K+G55P
    - 34+P+K44552+K
    - 6+P+K+G55P
    - 2+G__51+K+G
    - 1+P+K
    - P+KP5P
    - 2+KP5K
    - PPK
    - 4+PK5P
    - 3+PP5K
    - 41236+P5P
    - 4+KP5P
  - Punish Low
    - 6+P+K+G552+K #recoverslow
    - 51+K #recoverslow
    - 9+G5K #recoverslow
    - 1+K+G