CharacterName: [B]rad
Categories:
  - Punishable
    - PPPK
    - 66+K
    - P56+PK
    - 6+PK
    - 9+K
    - P+K5P5P
    - 3+P+KP
    - 6+K+G
  - Punishable Low
    - PPK
    - 1+P
    - 1+K
    - K+G5K
    - 2+K+G
    - 1+K+G
