CharacterName: [G]oh
Categories:
  - Charge
    - 4+K+P_____ #fullcharge
  - Punishable Low
    - 8+K+G #hitslow
    - 2+K+G #hitslow
    - 2+K #recoverslow
    - 1+K #hitslow
    - 9+G5K #hitslow
  - Punishable
    - 33+P #throwcounterable
    - 4+K #throwcounterable
    - 3+KP
    - 46P+KP6+P
    - 3+P+K #throwcounterable
    - 1+P+K
    - 4+K+G
    - 66P+G #throwcounterable