CharacterName: Jeff[r]y
Categories:
  - Charge    
    - 41236+P______ #fullcharge
  - Punishable
    - PKP #throwcounterable
    - 66+G+K55P+GP+G
    - 66+G+K5556+P
    - KPP55P+GP+G
    - KPP5556+P
    - PPP
    - 6+PP
    - 43+P5P
    - 3+PP
    - 33+P
    - 1+PP
    - KP5K
    - 6+K
    - 2+KP
    - G+K+PPP
  - Punishable Low
    - 9+G5P #recoverslow
    - 2+G__5551+K #recoverslow
    - 2+G__5552+K+G #hitslow
    - 1+P+K5K #hitslow