CharacterName: "[L]au"
Categories:
  - Punishable
    - 44+P52+K
    - PPPK
    - PPP57+K
    - P54+PP
    - 4+PKP
    - 44+PK+G
    - 2_3+PP+K
    - 3346+P
    - 3+PPPK
    - 3+PPP7+K
    - 3+KPP
    - 9+K
    - 7+K
    - 3+P+K
    - 6+K+G
    - 9+K+GP
    - K+G55PPP
    - K+G5K
    - K+G5K+GK    
    - 44+P58+K+G
  - Punishable (Low)
    - 9+G5K
    - 52+K+G
    - 5PPP2+K
    - 553+PPP2+K
  - Charge
    - P+K_____