CharacterName: Lei-[F]ei
Categories:
  - Punishable Kyo Shiki
    - 4+P+K+G5PP52+K #recoverslow
    - 4+P+K+G5K5K 
    - 4+P+K+G552+K5K #recoverslow
  - Punishable Suirakan Shiki
    - 33+K+GK5555K #recoverslow
    - 33+K+GK5555P+K
  - Punishable Nehan Shiki
    - 1+P+K+G52+K #recoverslow
    - 1+P+K+G5P+KP5PP
  - Punishable Dokuritsu Shiki
    - 8+P+K+G54+KKK #recoverslow
    - 8+P+K+G58+K+G #recoverslow
    - 8+P+K+G52+K+G #recoverslow
    - 8+P+K+G5KK
  - Punishable Hai Shiki
    - 2+P+K+G52+K #recoverslow
  - Punishable
    - 9+K+G #throwcounterable
    - 33+K+GKK+G #todoshadowhammer
    - 4+K+GKK #recoverslow
    - 3+K+G5K
    - 1+P+K
    - 4+P+K5P
    - 43+P+K
    - 6+P+KP5P
    - P+KP55P
    - 33+PP
    - 8+K5K
    - 9+K
  - Punishable Low
    - 9+G5K #recoverslow
    - 2+G+K #recoverslow
    - 2+K #hitslow