CharacterName: [P]ai
Categories:
  - Punishable
    - 7+K
    - PPP52+K
  - Charge
    - 3+PK_____
  - Fuzzy on guard
    - 4+P5P+GP+GP+G
    - 4+P5556+P6+P6+P6+P6+P6+P6+P
    - 46+K+G55P+G
    - 46+K+G5556+P6+P    
  - PPP Mixup
    - PPP52+K
    - PPP55P+G
    - PPP57+K
    - PPP5K