CharacterName: [S]arah
Categories:
  - Punishable Back Turned
    - 44+P552+K
    - 44+P551+K
    - 44+P55P+KK
  - Punishable Flamingo
    - 4+KG5P2+K
    - 4+KG5KKKK
    - 4+KG56+K5K
    - 4+KG57+K
    - 4+KG56+K+G
    - 4+KG52+K+G
  - Punishable Forward Slide
    - 6+P+K+G552+K
    - 6+P+K+G5PPK
  - Punishable Back Slide
    - 6+P+K+G5452+K
    - 6+P+K+G545K+G
  - Punishable basics
    - 9+K+GPP55K
    - 1+K
    - 9+K
    - 7+K
    - 2+P+KK
    - 2+G__KK
    - 2+G__K55K
    - KK
    - 4+PK554+K
    - 6+PK
    - PPPK
    - PPP7+K
  - Punishable Low
    - 52+K
    - 52+K+G
    - 53+K+G
    - 9+G5K #recoverslow